spring:
  data:
    mongodb:
      username: root
      password: 135135won
      host: localhost
      port: 27017
      database: msa_project
      # ref : https://www.mongodb.com/community/forums/t/objects-getting-auto-saved-in-test-database-instead-of-user-database/234137/2
      # mongodb+srv://user:pass@gettingstarted.x000y.mongodb.net/DbName?retryWrites=true&w=majority
      # uri: mongodb://root:135135won@localhost:27017/msa_project?retryWrites=true&w=majority
      # uri: mongodb://root:135135won@localhost:27017/msa_project?retryWrites=true&w=majority
      authentication-database: admin

server:
  port: 8090


# 반드시 체킹할 것

# 1. spring.config.import: optional:configserver:http://localhost:8888
# 2. spring.application.name: customer-service

# 3. config-server에 @EnableConfigServer 어노테이션이 있어야 함

# 4. mongo db는 admin, local, config와 같은 기본 db가 있는데 admin에 사용할 계정을 등록해둬야 연결되어 작동됨.
# 5. admin에 계정 등록할 때는 아래와 같이 명령어를 사용함
# use admin
# db.createUser
# (
#   {
#     user : "root",
#     pwd : "135135won",
#     roles: [ { role: "root", db: "admin" } ]
#   })


# 그다음 config server는 다음과 같이 구성
#spring:
#  data:
#    mongodb:
#      username: root
#      password: 135135won
#      host: localhost
#      port: 27017
#      database: msa_project
#      # ref : https://www.mongodb.com/community/forums/t/objects-getting-auto-saved-in-test-database-instead-of-user-database/234137/2
#      # mongodb+srv://user:pass@gettingstarted.x000y.mongodb.net/DbName?retryWrites=true&w=majority
#      # uri: mongodb://root:135135won@localhost:27017/msa_project?retryWrites=true&w=majority
#      # uri: mongodb://root:135135won@localhost:27017/msa_project?retryWrites=true&w=majority
#      authentication-database: admin