
## want to add postgresql
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_cloud
    username: root
    password: 135135won
    driver-class-name: org.postgresql.Driver

  # if table not exist, create table
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect


  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}



server:
  port: 8050